CREATE TABLE "character" (
  "character_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "alias" varchar,
  "category" varchar,
  "status" varchar,
  "power_type" varchar,
  "threat_level" int,
  "origin_note" text,
  "debut_date" date,
  "is_team_only" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "power" (
  "power_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "category" varchar
);

CREATE TABLE "character_power" (
  "character_id" int,
  "power_id" int
);

CREATE TABLE "team" (
  "team_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_name" varchar,
  "formed_date" date
);

CREATE TABLE "team_membership" (
  "membership_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" int,
  "team_id" int,
  "joined_date" date,
  "left_date" date
);

CREATE TABLE "battle" (
  "battle_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "battle_date" date,
  "outcome" varchar,
  "description" text
);

CREATE TABLE "battle_participant" (
  "battle_id" int,
  "character_id" int,
  "role" varchar,
  "result_note" text
);

CREATE TABLE "character_status_history" (
  "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" int,
  "old_status" varchar,
  "new_status" varchar,
  "changed_at" timestamp,
  "reason" text,
  "battle_id" int
);

ALTER TABLE "character_power" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "character_power" ADD FOREIGN KEY ("power_id") REFERENCES "power" ("power_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "team_membership" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "team_membership" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("team_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "battle_participant" ADD FOREIGN KEY ("battle_id") REFERENCES "battle" ("battle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "battle_participant" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "character_status_history" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "character_status_history" ADD FOREIGN KEY ("battle_id") REFERENCES "battle" ("battle_id") DEFERRABLE INITIALLY IMMEDIATE;
