-- =========================================================
-- CAPEWATCH-DB: Team + TeamMembership seed data
-- Run AFTER 01_character_seed.sql
-- =========================================================

INSERT INTO team (team_name, formed_date) VALUES
('The Vanguard Circuit', '2011-05-01'),
('Ashfall Company', '2012-09-10'),
('The Greenward Order', '2017-09-01'),
('Frostline Division', '2014-11-01'),
('The Warpstine Cabal', '2015-01-01'),
('Duskveil Syndicate Command', '2010-09-09'),
('Retired Guard (Legacy Roster)', '2009-01-01'),
('Rookie Watch Program', '2025-01-01');

INSERT INTO team_membership (character_id, team_id, joined_date, left_date) VALUES
((SELECT character_id FROM character WHERE name = 'Voltframe'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2011-05-01', NULL),
((SELECT character_id FROM character WHERE name = 'Ironclad Sentinel'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2014-06-01', NULL),
((SELECT character_id FROM character WHERE name = 'Skylark Prime'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2011-05-01', NULL),
((SELECT character_id FROM character WHERE name = 'Duskrunner'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2013-01-15', NULL),
((SELECT character_id FROM character WHERE name = 'Copperhawk'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2013-08-01', NULL),
((SELECT character_id FROM character WHERE name = 'Skylark Junior'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2020-05-01', NULL),
((SELECT character_id FROM character WHERE name = 'Duskrunner''s Wingman'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2019-06-01', NULL),
((SELECT character_id FROM character WHERE name = 'Second Shield'), (SELECT team_id FROM team WHERE team_name = 'The Vanguard Circuit'), '2020-03-01', NULL),
((SELECT character_id FROM character WHERE name = 'Cinderwatch'), (SELECT team_id FROM team WHERE team_name = 'Ashfall Company'), '2012-09-10', NULL),
((SELECT character_id FROM character WHERE name = 'Ridgeback'), (SELECT team_id FROM team WHERE team_name = 'Ashfall Company'), '2012-10-01', NULL),
((SELECT character_id FROM character WHERE name = 'Emberlynx'), (SELECT team_id FROM team WHERE team_name = 'Ashfall Company'), '2016-03-01', NULL),
((SELECT character_id FROM character WHERE name = 'Grimtide'), (SELECT team_id FROM team WHERE team_name = 'Ashfall Company'), '2013-10-01', NULL),
((SELECT character_id FROM character WHERE name = 'Little Ridgeback'), (SELECT team_id FROM team WHERE team_name = 'Ashfall Company'), '2021-07-01', NULL),
((SELECT character_id FROM character WHERE name = 'Backline Warden'), (SELECT team_id FROM team WHERE team_name = 'Ashfall Company'), '2019-11-01', NULL),
((SELECT character_id FROM character WHERE name = 'Thornveil'), (SELECT team_id FROM team WHERE team_name = 'The Greenward Order'), '2017-09-01', NULL),
((SELECT character_id FROM character WHERE name = 'Bramblewitch'), (SELECT team_id FROM team WHERE team_name = 'The Greenward Order'), '2017-09-01', NULL),
((SELECT character_id FROM character WHERE name = 'Thornseed'), (SELECT team_id FROM team WHERE team_name = 'The Greenward Order'), '2021-10-01', NULL),
((SELECT character_id FROM character WHERE name = 'Bramblesprout'), (SELECT team_id FROM team WHERE team_name = 'The Greenward Order'), '2025-04-06', NULL),
((SELECT character_id FROM character WHERE name = 'Frostbyte'), (SELECT team_id FROM team WHERE team_name = 'Frostline Division'), '2014-11-01', NULL),
((SELECT character_id FROM character WHERE name = 'Gale Warden'), (SELECT team_id FROM team WHERE team_name = 'Frostline Division'), '2016-12-01', NULL),
((SELECT character_id FROM character WHERE name = 'Frostbyte''s Echo'), (SELECT team_id FROM team WHERE team_name = 'Frostline Division'), '2020-12-01', NULL),
((SELECT character_id FROM character WHERE name = 'Auravance'), (SELECT team_id FROM team WHERE team_name = 'Frostline Division'), '2018-04-01', NULL),
((SELECT character_id FROM character WHERE name = 'The Silent Auravance Partner'), (SELECT team_id FROM team WHERE team_name = 'Frostline Division'), '2020-07-01', NULL),
((SELECT character_id FROM character WHERE name = 'Doctor Warpstine'), (SELECT team_id FROM team WHERE team_name = 'The Warpstine Cabal'), '2015-01-01', NULL),
((SELECT character_id FROM character WHERE name = 'The Hollow King'), (SELECT team_id FROM team WHERE team_name = 'The Warpstine Cabal'), '2015-01-01', NULL),
((SELECT character_id FROM character WHERE name = 'Voidmask'), (SELECT team_id FROM team WHERE team_name = 'The Warpstine Cabal'), '2015-03-09', NULL),
((SELECT character_id FROM character WHERE name = 'Chronarch'), (SELECT team_id FROM team WHERE team_name = 'The Warpstine Cabal'), '2015-01-01', NULL),
((SELECT character_id FROM character WHERE name = 'Duskveil Syndicate'), (SELECT team_id FROM team WHERE team_name = 'Duskveil Syndicate Command'), '2010-09-09', NULL),
((SELECT character_id FROM character WHERE name = 'Ferrotide'), (SELECT team_id FROM team WHERE team_name = 'Duskveil Syndicate Command'), '2012-10-20', NULL),
((SELECT character_id FROM character WHERE name = 'The Gilded Tyrant'), (SELECT team_id FROM team WHERE team_name = 'Duskveil Syndicate Command'), '2013-07-04', NULL),
((SELECT character_id FROM character WHERE name = 'Nullwick''s Redemption Arc'), (SELECT team_id FROM team WHERE team_name = 'Duskveil Syndicate Command'), '2016-01-01', '2019-03-03'),
((SELECT character_id FROM character WHERE name = 'The Quiet Ferrotide Ally'), (SELECT team_id FROM team WHERE team_name = 'Duskveil Syndicate Command'), '2018-08-08', NULL),
((SELECT character_id FROM character WHERE name = 'Old Ironvow'), (SELECT team_id FROM team WHERE team_name = 'Retired Guard (Legacy Roster)'), '2009-01-01', '2020-01-01'),
((SELECT character_id FROM character WHERE name = 'The Last Gale Warden'), (SELECT team_id FROM team WHERE team_name = 'Retired Guard (Legacy Roster)'), '2010-01-01', '2021-01-01'),
((SELECT character_id FROM character WHERE name = 'Auravance Sr.'), (SELECT team_id FROM team WHERE team_name = 'Retired Guard (Legacy Roster)'), '2011-01-01', '2022-01-01'),
((SELECT character_id FROM character WHERE name = 'Duskrunner Classic'), (SELECT team_id FROM team WHERE team_name = 'Retired Guard (Legacy Roster)'), '2009-06-01', '2020-06-01'),
((SELECT character_id FROM character WHERE name = 'Emberlynx Prime'), (SELECT team_id FROM team WHERE team_name = 'Retired Guard (Legacy Roster)'), '2010-02-01', '2021-02-01'),
((SELECT character_id FROM character WHERE name = 'Nightglass Elder'), (SELECT team_id FROM team WHERE team_name = 'Retired Guard (Legacy Roster)'), '2010-05-01', '2022-05-01'),
((SELECT character_id FROM character WHERE name = 'Static Spark'), (SELECT team_id FROM team WHERE team_name = 'Rookie Watch Program'), '2025-01-10', NULL),
((SELECT character_id FROM character WHERE name = 'Trainee Wraith'), (SELECT team_id FROM team WHERE team_name = 'Rookie Watch Program'), '2025-02-14', NULL),
((SELECT character_id FROM character WHERE name = 'Fledge'), (SELECT team_id FROM team WHERE team_name = 'Rookie Watch Program'), '2025-03-01', NULL),
((SELECT character_id FROM character WHERE name = 'Cadet Ironclad'), (SELECT team_id FROM team WHERE team_name = 'Rookie Watch Program'), '2025-01-25', NULL),
((SELECT character_id FROM character WHERE name = 'Half-Charge'), (SELECT team_id FROM team WHERE team_name = 'Rookie Watch Program'), '2025-02-28', NULL),
((SELECT character_id FROM character WHERE name = 'Bramblesprout'), (SELECT team_id FROM team WHERE team_name = 'Rookie Watch Program'), '2025-04-05', NULL);
