-- =========================================================
-- CAPEWATCH-DB: Power + CharacterPower seed data
-- Run AFTER 01_character_seed.sql (and 02_add_aliases.sql)
-- =========================================================

-- Distinct powers extracted from the character roster
INSERT INTO power (name, category) VALUES
('Electrokinesis', 'Other'),
('Fire Manipulation', 'Elemental'),
('Water Control', 'Elemental'),
('Ice Control', 'Elemental'),
('Flight', 'Physical'),
('Sonic Scream', 'Physical'),
('Powered Exosuit', 'Tech'),
('Teleportation', 'Spatial'),
('Enhanced Agility', 'Physical'),
('Retractable Claws', 'Physical'),
('Cosmic Energy Projection', 'Cosmic'),
('Light Manipulation', 'Elemental'),
('Illusion Casting', 'Mental'),
('Plant Manipulation', 'Other'),
('Super Strength', 'Physical'),
('Cryokinesis', 'Other'),
('Energy Shields', 'Other'),
('Empathy', 'Mental'),
('Super Speed', 'Physical'),
('Magnetism Control', 'Elemental'),
('Light Constructs', 'Elemental'),
('Wind Control', 'Elemental'),
('Weather Control', 'Elemental'),
('Gadgetry', 'Tech'),
('Detective Skill', 'Mental'),
('Nature Magic', 'Magic'),
('Healing', 'Magic'),
('Bone Manipulation', 'Physical'),
('Assassination Skill', 'Physical'),
('Combat Mastery', 'Physical'),
('Lycanthropic Traits', 'Physical'),
('Curse Casting', 'Magic'),
('Junk-Tech Engineering', 'Tech'),
('Sound Manipulation', 'Elemental'),
('Power Nullification', 'Mental'),
('Spirit Communication', 'Mental'),
('Cybernetic Augmentation', 'Tech'),
('Poison Manipulation', 'Elemental'),
('Lava Manipulation', 'Elemental'),
('Heat Manipulation', 'Elemental'),
('Reality Distortion', 'Cosmic'),
('Mind Control', 'Mental'),
('Possession', 'Mental'),
('Metal Manipulation', 'Elemental'),
('Plague Manipulation', 'Elemental'),
('Decay Manipulation', 'Elemental'),
('Time Manipulation', 'Cosmic'),
('Shadow Manipulation', 'Elemental'),
('Dimensional Travel', 'Cosmic'),
('Wealth', 'Tech'),
('Resources', 'Other'),
('Private Military Tech', 'Tech'),
('Electricity Manipulation', 'Elemental'),
('Spatial Trap Creation', 'Spatial'),
('Organized Crime Network', 'Other'),
('Drowning Manipulation', 'Elemental'),
('Glass Manipulation', 'Elemental'),
('Crystal Manipulation', 'Elemental'),
('Logistics', 'Other'),
('Support', 'Other'),
('Unknown', 'Other'),
('Fire Resistance', 'Elemental'),
('Decay Resistance', 'Elemental');

-- Character <-> Power mapping (name-based lookups, safe regardless of actual generated IDs)
INSERT INTO character_power (character_id, power_id) VALUES
((SELECT character_id FROM character WHERE name = 'Voltframe'), (SELECT power_id FROM power WHERE name = 'Electrokinesis')),
((SELECT character_id FROM character WHERE name = 'Cinderwatch'), (SELECT power_id FROM power WHERE name = 'Fire Manipulation')),
((SELECT character_id FROM character WHERE name = 'Grimtide'), (SELECT power_id FROM power WHERE name = 'Water Control')),
((SELECT character_id FROM character WHERE name = 'Grimtide'), (SELECT power_id FROM power WHERE name = 'Ice Control')),
((SELECT character_id FROM character WHERE name = 'Skylark Prime'), (SELECT power_id FROM power WHERE name = 'Flight')),
((SELECT character_id FROM character WHERE name = 'Skylark Prime'), (SELECT power_id FROM power WHERE name = 'Sonic Scream')),
((SELECT character_id FROM character WHERE name = 'Ironclad Sentinel'), (SELECT power_id FROM power WHERE name = 'Powered Exosuit')),
((SELECT character_id FROM character WHERE name = 'Wraithstep'), (SELECT power_id FROM power WHERE name = 'Teleportation')),
((SELECT character_id FROM character WHERE name = 'Emberlynx'), (SELECT power_id FROM power WHERE name = 'Enhanced Agility')),
((SELECT character_id FROM character WHERE name = 'Emberlynx'), (SELECT power_id FROM power WHERE name = 'Retractable Claws')),
((SELECT character_id FROM character WHERE name = 'Starforge'), (SELECT power_id FROM power WHERE name = 'Cosmic Energy Projection')),
((SELECT character_id FROM character WHERE name = 'Nightglass'), (SELECT power_id FROM power WHERE name = 'Light Manipulation')),
((SELECT character_id FROM character WHERE name = 'Nightglass'), (SELECT power_id FROM power WHERE name = 'Illusion Casting')),
((SELECT character_id FROM character WHERE name = 'Thornveil'), (SELECT power_id FROM power WHERE name = 'Plant Manipulation')),
((SELECT character_id FROM character WHERE name = 'Ridgeback'), (SELECT power_id FROM power WHERE name = 'Super Strength')),
((SELECT character_id FROM character WHERE name = 'Frostbyte'), (SELECT power_id FROM power WHERE name = 'Cryokinesis')),
((SELECT character_id FROM character WHERE name = 'Auravance'), (SELECT power_id FROM power WHERE name = 'Energy Shields')),
((SELECT character_id FROM character WHERE name = 'Auravance'), (SELECT power_id FROM power WHERE name = 'Empathy')),
((SELECT character_id FROM character WHERE name = 'Duskrunner'), (SELECT power_id FROM power WHERE name = 'Super Speed')),
((SELECT character_id FROM character WHERE name = 'Ironvow'), (SELECT power_id FROM power WHERE name = 'Magnetism Control')),
((SELECT character_id FROM character WHERE name = 'Lumen Cross'), (SELECT power_id FROM power WHERE name = 'Light Constructs')),
((SELECT character_id FROM character WHERE name = 'Gale Warden'), (SELECT power_id FROM power WHERE name = 'Wind Control')),
((SELECT character_id FROM character WHERE name = 'Gale Warden'), (SELECT power_id FROM power WHERE name = 'Weather Control')),
((SELECT character_id FROM character WHERE name = 'Copperhawk'), (SELECT power_id FROM power WHERE name = 'Gadgetry')),
((SELECT character_id FROM character WHERE name = 'Copperhawk'), (SELECT power_id FROM power WHERE name = 'Detective Skill')),
((SELECT character_id FROM character WHERE name = 'Bramblewitch'), (SELECT power_id FROM power WHERE name = 'Nature Magic')),
((SELECT character_id FROM character WHERE name = 'Bramblewitch'), (SELECT power_id FROM power WHERE name = 'Healing')),
((SELECT character_id FROM character WHERE name = 'Static Marrow'), (SELECT power_id FROM power WHERE name = 'Bone Manipulation')),
((SELECT character_id FROM character WHERE name = 'Redveil'), (SELECT power_id FROM power WHERE name = 'Assassination Skill')),
((SELECT character_id FROM character WHERE name = 'Redveil'), (SELECT power_id FROM power WHERE name = 'Combat Mastery')),
((SELECT character_id FROM character WHERE name = 'Fangmourn'), (SELECT power_id FROM power WHERE name = 'Lycanthropic Traits')),
((SELECT character_id FROM character WHERE name = 'Hexbroker'), (SELECT power_id FROM power WHERE name = 'Curse Casting')),
((SELECT character_id FROM character WHERE name = 'Scrapyard'), (SELECT power_id FROM power WHERE name = 'Junk-Tech Engineering')),
((SELECT character_id FROM character WHERE name = 'Ashen Choir'), (SELECT power_id FROM power WHERE name = 'Sound Manipulation')),
((SELECT character_id FROM character WHERE name = 'Nullwick'), (SELECT power_id FROM power WHERE name = 'Power Nullification')),
((SELECT character_id FROM character WHERE name = 'Graveharbor'), (SELECT power_id FROM power WHERE name = 'Spirit Communication')),
((SELECT character_id FROM character WHERE name = 'Ironsplice'), (SELECT power_id FROM power WHERE name = 'Cybernetic Augmentation')),
((SELECT character_id FROM character WHERE name = 'Duskthorn'), (SELECT power_id FROM power WHERE name = 'Poison Manipulation')),
((SELECT character_id FROM character WHERE name = 'Molten Vow'), (SELECT power_id FROM power WHERE name = 'Lava Manipulation')),
((SELECT character_id FROM character WHERE name = 'Molten Vow'), (SELECT power_id FROM power WHERE name = 'Heat Manipulation')),
((SELECT character_id FROM character WHERE name = 'Doctor Warpstine'), (SELECT power_id FROM power WHERE name = 'Reality Distortion')),
((SELECT character_id FROM character WHERE name = 'The Hollow King'), (SELECT power_id FROM power WHERE name = 'Mind Control')),
((SELECT character_id FROM character WHERE name = 'The Hollow King'), (SELECT power_id FROM power WHERE name = 'Possession')),
((SELECT character_id FROM character WHERE name = 'Ferrotide'), (SELECT power_id FROM power WHERE name = 'Metal Manipulation')),
((SELECT character_id FROM character WHERE name = 'Blightmother'), (SELECT power_id FROM power WHERE name = 'Plague Manipulation')),
((SELECT character_id FROM character WHERE name = 'Blightmother'), (SELECT power_id FROM power WHERE name = 'Decay Manipulation')),
((SELECT character_id FROM character WHERE name = 'Chronarch'), (SELECT power_id FROM power WHERE name = 'Time Manipulation')),
((SELECT character_id FROM character WHERE name = 'Voidmask'), (SELECT power_id FROM power WHERE name = 'Shadow Manipulation')),
((SELECT character_id FROM character WHERE name = 'Voidmask'), (SELECT power_id FROM power WHERE name = 'Dimensional Travel')),
((SELECT character_id FROM character WHERE name = 'The Gilded Tyrant'), (SELECT power_id FROM power WHERE name = 'Wealth')),
((SELECT character_id FROM character WHERE name = 'The Gilded Tyrant'), (SELECT power_id FROM power WHERE name = 'Resources')),
((SELECT character_id FROM character WHERE name = 'The Gilded Tyrant'), (SELECT power_id FROM power WHERE name = 'Private Military Tech')),
((SELECT character_id FROM character WHERE name = 'Emberfall'), (SELECT power_id FROM power WHERE name = 'Fire Manipulation')),
((SELECT character_id FROM character WHERE name = 'Static Regent'), (SELECT power_id FROM power WHERE name = 'Electricity Manipulation')),
((SELECT character_id FROM character WHERE name = 'Marrow Queen'), (SELECT power_id FROM power WHERE name = 'Bone Manipulation')),
((SELECT character_id FROM character WHERE name = 'The Cartographer'), (SELECT power_id FROM power WHERE name = 'Teleportation')),
((SELECT character_id FROM character WHERE name = 'The Cartographer'), (SELECT power_id FROM power WHERE name = 'Spatial Trap Creation')),
((SELECT character_id FROM character WHERE name = 'Duskveil Syndicate'), (SELECT power_id FROM power WHERE name = 'Organized Crime Network')),
((SELECT character_id FROM character WHERE name = 'Ironclad Usurper'), (SELECT power_id FROM power WHERE name = 'Powered Exosuit')),
((SELECT character_id FROM character WHERE name = 'The Undertow'), (SELECT power_id FROM power WHERE name = 'Water Control')),
((SELECT character_id FROM character WHERE name = 'The Undertow'), (SELECT power_id FROM power WHERE name = 'Drowning Manipulation')),
((SELECT character_id FROM character WHERE name = 'Nightshard'), (SELECT power_id FROM power WHERE name = 'Glass Manipulation')),
((SELECT character_id FROM character WHERE name = 'Nightshard'), (SELECT power_id FROM power WHERE name = 'Crystal Manipulation')),
((SELECT character_id FROM character WHERE name = 'Skylark Junior'), (SELECT power_id FROM power WHERE name = 'Flight')),
((SELECT character_id FROM character WHERE name = 'Skylark Junior'), (SELECT power_id FROM power WHERE name = 'Sonic Scream')),
((SELECT character_id FROM character WHERE name = 'Little Ridgeback'), (SELECT power_id FROM power WHERE name = 'Super Strength')),
((SELECT character_id FROM character WHERE name = 'Frostbyte''s Echo'), (SELECT power_id FROM power WHERE name = 'Cryokinesis')),
((SELECT character_id FROM character WHERE name = 'Copperhawk II'), (SELECT power_id FROM power WHERE name = 'Gadgetry')),
((SELECT character_id FROM character WHERE name = 'Copperhawk II'), (SELECT power_id FROM power WHERE name = 'Detective Skill')),
((SELECT character_id FROM character WHERE name = 'Thornseed'), (SELECT power_id FROM power WHERE name = 'Plant Manipulation')),
((SELECT character_id FROM character WHERE name = 'Old Ironvow'), (SELECT power_id FROM power WHERE name = 'Magnetism Control')),
((SELECT character_id FROM character WHERE name = 'The Last Gale Warden'), (SELECT power_id FROM power WHERE name = 'Wind Control')),
((SELECT character_id FROM character WHERE name = 'The Last Gale Warden'), (SELECT power_id FROM power WHERE name = 'Weather Control')),
((SELECT character_id FROM character WHERE name = 'Auravance Sr.'), (SELECT power_id FROM power WHERE name = 'Energy Shields')),
((SELECT character_id FROM character WHERE name = 'Auravance Sr.'), (SELECT power_id FROM power WHERE name = 'Empathy')),
((SELECT character_id FROM character WHERE name = 'Duskrunner Classic'), (SELECT power_id FROM power WHERE name = 'Super Speed')),
((SELECT character_id FROM character WHERE name = 'Emberlynx Prime'), (SELECT power_id FROM power WHERE name = 'Enhanced Agility')),
((SELECT character_id FROM character WHERE name = 'Emberlynx Prime'), (SELECT power_id FROM power WHERE name = 'Retractable Claws')),
((SELECT character_id FROM character WHERE name = 'Nightglass Elder'), (SELECT power_id FROM power WHERE name = 'Light Manipulation')),
((SELECT character_id FROM character WHERE name = 'Nightglass Elder'), (SELECT power_id FROM power WHERE name = 'Illusion Casting')),
((SELECT character_id FROM character WHERE name = 'Static Spark'), (SELECT power_id FROM power WHERE name = 'Bone Manipulation')),
((SELECT character_id FROM character WHERE name = 'Trainee Wraith'), (SELECT power_id FROM power WHERE name = 'Teleportation')),
((SELECT character_id FROM character WHERE name = 'Fledge'), (SELECT power_id FROM power WHERE name = 'Flight')),
((SELECT character_id FROM character WHERE name = 'Cadet Ironclad'), (SELECT power_id FROM power WHERE name = 'Powered Exosuit')),
((SELECT character_id FROM character WHERE name = 'Bramblesprout'), (SELECT power_id FROM power WHERE name = 'Nature Magic')),
((SELECT character_id FROM character WHERE name = 'Bramblesprout'), (SELECT power_id FROM power WHERE name = 'Healing')),
((SELECT character_id FROM character WHERE name = 'Half-Charge'), (SELECT power_id FROM power WHERE name = 'Electrokinesis')),
((SELECT character_id FROM character WHERE name = 'Duskrunner''s Wingman'), (SELECT power_id FROM power WHERE name = 'Super Speed')),
((SELECT character_id FROM character WHERE name = 'The Quiet Ferrotide Ally'), (SELECT power_id FROM power WHERE name = 'Metal Manipulation')),
((SELECT character_id FROM character WHERE name = 'Backline Warden'), (SELECT power_id FROM power WHERE name = 'Logistics')),
((SELECT character_id FROM character WHERE name = 'Backline Warden'), (SELECT power_id FROM power WHERE name = 'Support')),
((SELECT character_id FROM character WHERE name = 'Second Shield'), (SELECT power_id FROM power WHERE name = 'Energy Shields')),
((SELECT character_id FROM character WHERE name = 'The Silent Auravance Partner'), (SELECT power_id FROM power WHERE name = 'Empathy')),
((SELECT character_id FROM character WHERE name = 'Roster Filler Unit'), (SELECT power_id FROM power WHERE name = 'Unknown')),
((SELECT character_id FROM character WHERE name = 'Nullwick''s Redemption Arc'), (SELECT power_id FROM power WHERE name = 'Power Nullification')),
((SELECT character_id FROM character WHERE name = 'Ashwake'), (SELECT power_id FROM power WHERE name = 'Fire Resistance')),
((SELECT character_id FROM character WHERE name = 'Ashwake'), (SELECT power_id FROM power WHERE name = 'Decay Resistance')),
((SELECT character_id FROM character WHERE name = 'The Former Undertow'), (SELECT power_id FROM power WHERE name = 'Water Control')),
((SELECT character_id FROM character WHERE name = 'The Former Undertow'), (SELECT power_id FROM power WHERE name = 'Drowning Manipulation')),
((SELECT character_id FROM character WHERE name = 'Graveharbor Reclaimed'), (SELECT power_id FROM power WHERE name = 'Spirit Communication'));
